project_id = "xrptjdntnwnxpehsswvn"

[functions.create-virtual-account]
verify_jwt = false

[functions.paymentpoint-webhook]
verify_jwt = false

[functions.buy-data]
verify_jwt = false

[functions.buy-airtime]
verify_jwt = false

[functions.data-webhook]
verify_jwt = false

[functions.buy-electricity]
verify_jwt = false

[functions.buy-cable]
verify_jwt = false

[functions.buy-exam-pin]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.admin-data]
verify_jwt = false

[functions.sync-data-plans]
verify_jwt = false